services:
  database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=account'
      - 'POSTGRES_DB=money_transfer_db'
      - 'POSTGRES_PASSWORD=password'