spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/money_transfer_db
    username: account
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      file: src/main/java/com/money/transfer/money_transfer/docker/docker-compose.yaml